using System;
using System.Collections.Generic;

namespace AllYourTextsLib
{
    public static class CountryCallingCodeFinder
    {
        //
        // Abbreviations that the iPhone uses to represent different countries. Seems to be ISO 3166-1 alpha-2 codes.
        // The following have been confirmed in the wild: US, Canada, UK, Israel
        //

        public const string CountryAbbreviationAfghanistan                  = "af";
        public const string CountryAbbreviationAlbania                      = "al";
        public const string CountryAbbreviationAlgeria                      = "dz";
        public const string CountryAbbreviationAmericanSamoa                = "as";
        public const string CountryAbbreviationAndorra                      = "ad";
        public const string CountryAbbreviationAngola                       = "ao";
        public const string CountryAbbreviationAnguilla                     = "ai";
        public const string CountryAbbreviationAntarctica                   = "aq";
        public const string CountryAbbreviationAntiguaandBarbuda            = "ag";
        public const string CountryAbbreviationArgentina                    = "ar";
        public const string CountryAbbreviationArmenia                      = "am";
        public const string CountryAbbreviationAruba                        = "aw";
        public const string CountryAbbreviationAustralia                    = "au";
        public const string CountryAbbreviationAustria                      = "at";
        public const string CountryAbbreviationAzerbaijan                   = "az";
        public const string CountryAbbreviationBahamas                      = "bs";
        public const string CountryAbbreviationBahrain                      = "bh";
        public const string CountryAbbreviationBangladesh                   = "bd";
        public const string CountryAbbreviationBarbados                     = "bb";
        public const string CountryAbbreviationBelarus                      = "by";
        public const string CountryAbbreviationBelgium                      = "be";
        public const string CountryAbbreviationBelize                       = "bz";
        public const string CountryAbbreviationBenin                        = "bj";
        public const string CountryAbbreviationBermuda                      = "bm";
        public const string CountryAbbreviationBhutan                       = "bt";
        public const string CountryAbbreviationBolivia                      = "bo";
        public const string CountryAbbreviationBosniaandHerzegovina         = "ba";
        public const string CountryAbbreviationBotswana                     = "bw";
        public const string CountryAbbreviationBrazil                       = "br";
        public const string CountryAbbreviationBritishVirginIslands         = "vg";
        public const string CountryAbbreviationBrunei                       = "bn";
        public const string CountryAbbreviationBulgaria                     = "bg";
        public const string CountryAbbreviationBurkinaFaso                  = "bf";
        public const string CountryAbbreviationBurmaMyanmar                 = "mm";
        public const string CountryAbbreviationBurundi                      = "bi";
        public const string CountryAbbreviationCambodia                     = "kh";
        public const string CountryAbbreviationCameroon                     = "cm";
        public const string CountryAbbreviationCanada                       = "ca";
        public const string CountryAbbreviationCapeVerde                    = "cv";
        public const string CountryAbbreviationCaymanIslands                = "ky";
        public const string CountryAbbreviationCentralAfricanRepublic       = "cf";
        public const string CountryAbbreviationChad                         = "td";
        public const string CountryAbbreviationChile                        = "cl";
        public const string CountryAbbreviationChina                        = "cn";
        public const string CountryAbbreviationChristmasIsland              = "cx";
        public const string CountryAbbreviationCocosKeelingIslands          = "cc";
        public const string CountryAbbreviationColombia                     = "co";
        public const string CountryAbbreviationComoros                      = "km";
        public const string CountryAbbreviationCookIslands                  = "ck";
        public const string CountryAbbreviationCostaRica                    = "cr";
        public const string CountryAbbreviationCroatia                      = "hr";
        public const string CountryAbbreviationCuba                         = "cu";
        public const string CountryAbbreviationCyprus                       = "cy";
        public const string CountryAbbreviationCzechRepublic                = "cz";
        public const string CountryAbbreviationDemocraticRepublicoftheCongo = "cd";
        public const string CountryAbbreviationDenmark                      = "dk";
        public const string CountryAbbreviationDjibouti                     = "dj";
        public const string CountryAbbreviationDominica                     = "dm";
        public const string CountryAbbreviationDominicanRepublic            = "do";
        public const string CountryAbbreviationEcuador                      = "ec";
        public const string CountryAbbreviationEgypt                        = "eg";
        public const string CountryAbbreviationElSalvador                   = "sv";
        public const string CountryAbbreviationEquatorialGuinea             = "gq";
        public const string CountryAbbreviationEritrea                      = "er";
        public const string CountryAbbreviationEstonia                      = "ee";
        public const string CountryAbbreviationEthiopia                     = "et";
        public const string CountryAbbreviationFalklandIslands              = "fk";
        public const string CountryAbbreviationFaroeIslands                 = "fo";
        public const string CountryAbbreviationFiji                         = "fj";
        public const string CountryAbbreviationFinland                      = "fi";
        public const string CountryAbbreviationFrance                       = "fr";
        public const string CountryAbbreviationFrenchPolynesia              = "pf";
        public const string CountryAbbreviationGabon                        = "ga";
        public const string CountryAbbreviationGambia                       = "gm";
        public const string CountryAbbreviationGeorgia                      = "ge";
        public const string CountryAbbreviationGermany                      = "de";
        public const string CountryAbbreviationGhana                        = "gh";
        public const string CountryAbbreviationGibraltar                    = "gi";
        public const string CountryAbbreviationGreece                       = "gr";
        public const string CountryAbbreviationGreenland                    = "gl";
        public const string CountryAbbreviationGrenada                      = "gd";
        public const string CountryAbbreviationGuam                         = "gu";
        public const string CountryAbbreviationGuatemala                    = "gt";
        public const string CountryAbbreviationGuinea                       = "gn";
        public const string CountryAbbreviationGuineaBissau                 = "gw";
        public const string CountryAbbreviationGuyana                       = "gy";
        public const string CountryAbbreviationHaiti                        = "ht";
        public const string CountryAbbreviationHolySeeVaticanCity           = "va";
        public const string CountryAbbreviationHonduras                     = "hn";
        public const string CountryAbbreviationHongKong                     = "hk";
        public const string CountryAbbreviationHungary                      = "hu";
        public const string CountryAbbreviationIceland                      = "is";
        public const string CountryAbbreviationIndia                        = "in";
        public const string CountryAbbreviationIndonesia                    = "id";
        public const string CountryAbbreviationIran                         = "ir";
        public const string CountryAbbreviationIraq                         = "iq";
        public const string CountryAbbreviationIreland                      = "ie";
        public const string CountryAbbreviationIsleofMan                    = "im";
        public const string CountryAbbreviationIsrael                       = "il";
        public const string CountryAbbreviationItaly                        = "it";
        public const string CountryAbbreviationIvoryCoast                   = "ci";
        public const string CountryAbbreviationJamaica                      = "jm";
        public const string CountryAbbreviationJapan                        = "jp";
        public const string CountryAbbreviationJersey                       = "je";
        public const string CountryAbbreviationJordan                       = "jo";
        public const string CountryAbbreviationKazakhstan                   = "kz";
        public const string CountryAbbreviationKenya                        = "ke";
        public const string CountryAbbreviationKiribati                     = "ki";
        public const string CountryAbbreviationKuwait                       = "kw";
        public const string CountryAbbreviationKyrgyzstan                   = "kg";
        public const string CountryAbbreviationLaos                         = "la";
        public const string CountryAbbreviationLatvia                       = "lv";
        public const string CountryAbbreviationLebanon                      = "lb";
        public const string CountryAbbreviationLesotho                      = "ls";
        public const string CountryAbbreviationLiberia                      = "lr";
        public const string CountryAbbreviationLibya                        = "ly";
        public const string CountryAbbreviationLiechtenstein                = "li";
        public const string CountryAbbreviationLithuania                    = "lt";
        public const string CountryAbbreviationLuxembourg                   = "lu";
        public const string CountryAbbreviationMacau                        = "mo";
        public const string CountryAbbreviationMacedonia                    = "mk";
        public const string CountryAbbreviationMadagascar                   = "mg";
        public const string CountryAbbreviationMalawi                       = "mw";
        public const string CountryAbbreviationMalaysia                     = "my";
        public const string CountryAbbreviationMaldives                     = "mv";
        public const string CountryAbbreviationMali                         = "ml";
        public const string CountryAbbreviationMalta                        = "mt";
        public const string CountryAbbreviationMarshallIslands              = "mh";
        public const string CountryAbbreviationMauritania                   = "mr";
        public const string CountryAbbreviationMauritius                    = "mu";
        public const string CountryAbbreviationMayotte                      = "yt";
        public const string CountryAbbreviationMexico                       = "mx";
        public const string CountryAbbreviationMicronesia                   = "fm";
        public const string CountryAbbreviationMoldova                      = "md";
        public const string CountryAbbreviationMonaco                       = "mc";
        public const string CountryAbbreviationMongolia                     = "mn";
        public const string CountryAbbreviationMontenegro                   = "me";
        public const string CountryAbbreviationMontserrat                   = "ms";
        public const string CountryAbbreviationMorocco                      = "ma";
        public const string CountryAbbreviationMozambique                   = "mz";
        public const string CountryAbbreviationNamibia                      = "na";
        public const string CountryAbbreviationNauru                        = "nr";
        public const string CountryAbbreviationNepal                        = "np";
        public const string CountryAbbreviationNetherlands                  = "nl";
        public const string CountryAbbreviationNetherlandsAntilles          = "an";
        public const string CountryAbbreviationNewCaledonia                 = "nc";
        public const string CountryAbbreviationNewZealand                   = "nz";
        public const string CountryAbbreviationNicaragua                    = "ni";
        public const string CountryAbbreviationNiger                        = "ne";
        public const string CountryAbbreviationNigeria                      = "ng";
        public const string CountryAbbreviationNiue                         = "nu";
        public const string CountryAbbreviationNorthKorea                   = "kp";
        public const string CountryAbbreviationNorthernMarianaIslands       = "mp";
        public const string CountryAbbreviationNorway                       = "no";
        public const string CountryAbbreviationOman                         = "om";
        public const string CountryAbbreviationPakistan                     = "pk";
        public const string CountryAbbreviationPalau                        = "pw";
        public const string CountryAbbreviationPanama                       = "pa";
        public const string CountryAbbreviationPapuaNewGuinea               = "pg";
        public const string CountryAbbreviationParaguay                     = "py";
        public const string CountryAbbreviationPeru                         = "pe";
        public const string CountryAbbreviationPhilippines                  = "ph";
        public const string CountryAbbreviationPitcairnIslands              = "pn";
        public const string CountryAbbreviationPoland                       = "pl";
        public const string CountryAbbreviationPortugal                     = "pt";
        public const string CountryAbbreviationPuertoRico                   = "pr";
        public const string CountryAbbreviationQatar                        = "qa";
        public const string CountryAbbreviationRepublicoftheCongo           = "cg";
        public const string CountryAbbreviationRomania                      = "ro";
        public const string CountryAbbreviationRussia                       = "ru";
        public const string CountryAbbreviationRwanda                       = "rw";
        public const string CountryAbbreviationSaintBarthelemy              = "bl";
        public const string CountryAbbreviationSaintHelena                  = "sh";
        public const string CountryAbbreviationSaintKittsandNevis           = "kn";
        public const string CountryAbbreviationSaintLucia                   = "lc";
        public const string CountryAbbreviationSaintMartin                  = "mf";
        public const string CountryAbbreviationSaintPierreandMiquelon       = "pm";
        public const string CountryAbbreviationSaintVincentandtheGrenadines = "vc";
        public const string CountryAbbreviationSamoa                        = "ws";
        public const string CountryAbbreviationSanMarino                    = "sm";
        public const string CountryAbbreviationSaoTomeandPrincipe           = "st";
        public const string CountryAbbreviationSaudiArabia                  = "sa";
        public const string CountryAbbreviationSenegal                      = "sn";
        public const string CountryAbbreviationSerbia                       = "rs";
        public const string CountryAbbreviationSeychelles                   = "sc";
        public const string CountryAbbreviationSierraLeone                  = "sl";
        public const string CountryAbbreviationSingapore                    = "sg";
        public const string CountryAbbreviationSlovakia                     = "sk";
        public const string CountryAbbreviationSlovenia                     = "si";
        public const string CountryAbbreviationSolomonIslands               = "sb";
        public const string CountryAbbreviationSomalia                      = "so";
        public const string CountryAbbreviationSouthAfrica                  = "za";
        public const string CountryAbbreviationSouthKorea                   = "kr";
        public const string CountryAbbreviationSpain                        = "es";
        public const string CountryAbbreviationSriLanka                     = "lk";
        public const string CountryAbbreviationSudan                        = "sd";
        public const string CountryAbbreviationSuriname                     = "sr";
        public const string CountryAbbreviationSwaziland                    = "sz";
        public const string CountryAbbreviationSweden                       = "se";
        public const string CountryAbbreviationSwitzerland                  = "ch";
        public const string CountryAbbreviationSyria                        = "sy";
        public const string CountryAbbreviationTaiwan                       = "tw";
        public const string CountryAbbreviationTajikistan                   = "tj";
        public const string CountryAbbreviationTanzania                     = "tz";
        public const string CountryAbbreviationThailand                     = "th";
        public const string CountryAbbreviationTimorLeste                   = "tl";
        public const string CountryAbbreviationTogo                         = "tg";
        public const string CountryAbbreviationTokelau                      = "tk";
        public const string CountryAbbreviationTonga                        = "to";
        public const string CountryAbbreviationTrinidadandTobago            = "tt";
        public const string CountryAbbreviationTunisia                      = "tn";
        public const string CountryAbbreviationTurkey                       = "tr";
        public const string CountryAbbreviationTurkmenistan                 = "tm";
        public const string CountryAbbreviationTurksandCaicosIslands        = "tc";
        public const string CountryAbbreviationTuvalu                       = "tv";
        public const string CountryAbbreviationUganda                       = "ug";
        public const string CountryAbbreviationUkraine                      = "ua";
        public const string CountryAbbreviationUnitedArabEmirates           = "ae";
        public const string CountryAbbreviationUnitedKingdom                = "uk";     // exception to the original standard
        public const string CountryAbbreviationUnitedStates                 = "us";
        public const string CountryAbbreviationUruguay                      = "uy";
        public const string CountryAbbreviationUSVirginIslands              = "vi";
        public const string CountryAbbreviationUzbekistan                   = "uz";
        public const string CountryAbbreviationVanuatu                      = "vu";
        public const string CountryAbbreviationVenezuela                    = "ve";
        public const string CountryAbbreviationVietnam                      = "vn";
        public const string CountryAbbreviationWallisandFutuna              = "wf";
        public const string CountryAbbreviationYemen                        = "ye";
        public const string CountryAbbreviationZambia                       = "zm";
        public const string CountryAbbreviationZimbabwe                     = "zw";

        private static Dictionary<string, string> _CountryCodeMappings;

        static CountryCallingCodeFinder()
        {
            _CountryCodeMappings = new Dictionary<string, string>();
            PopulateCountryCodeMappings();
        }

        public static string GetCountryCallingCode(string countryAbbreviation)
        {
            try
            {
                return _CountryCodeMappings[countryAbbreviation.ToLower()];
            }
            catch (KeyNotFoundException ex)
            {
                throw new ArgumentException("Unrecognized country abbreviation: " + countryAbbreviation, ex);
            }
        }

        private static void PopulateCountryCodeMappings()
        {
            _CountryCodeMappings.Add(CountryAbbreviationAfghanistan,                  "93");
            _CountryCodeMappings.Add(CountryAbbreviationAlbania,                      "355");
            _CountryCodeMappings.Add(CountryAbbreviationAlgeria,                      "213");
            _CountryCodeMappings.Add(CountryAbbreviationAmericanSamoa,                "1");
            _CountryCodeMappings.Add(CountryAbbreviationAndorra,                      "376");
            _CountryCodeMappings.Add(CountryAbbreviationAngola,                       "244");
            _CountryCodeMappings.Add(CountryAbbreviationAnguilla,                     "1");
            _CountryCodeMappings.Add(CountryAbbreviationAntarctica,                   "672");
            _CountryCodeMappings.Add(CountryAbbreviationAntiguaandBarbuda,            "1");
            _CountryCodeMappings.Add(CountryAbbreviationArgentina,                    "54");
            _CountryCodeMappings.Add(CountryAbbreviationArmenia,                      "374");
            _CountryCodeMappings.Add(CountryAbbreviationAruba,                        "297");
            _CountryCodeMappings.Add(CountryAbbreviationAustralia,                    "61");
            _CountryCodeMappings.Add(CountryAbbreviationAustria,                      "43");
            _CountryCodeMappings.Add(CountryAbbreviationAzerbaijan,                   "994");
            _CountryCodeMappings.Add(CountryAbbreviationBahamas,                      "1");
            _CountryCodeMappings.Add(CountryAbbreviationBahrain,                      "973");
            _CountryCodeMappings.Add(CountryAbbreviationBangladesh,                   "880");
            _CountryCodeMappings.Add(CountryAbbreviationBarbados,                     "1");
            _CountryCodeMappings.Add(CountryAbbreviationBelarus,                      "375");
            _CountryCodeMappings.Add(CountryAbbreviationBelgium,                      "32");
            _CountryCodeMappings.Add(CountryAbbreviationBelize,                       "501");
            _CountryCodeMappings.Add(CountryAbbreviationBenin,                        "229");
            _CountryCodeMappings.Add(CountryAbbreviationBermuda,                      "1");
            _CountryCodeMappings.Add(CountryAbbreviationBhutan,                       "975");
            _CountryCodeMappings.Add(CountryAbbreviationBolivia,                      "591");
            _CountryCodeMappings.Add(CountryAbbreviationBosniaandHerzegovina,         "387");
            _CountryCodeMappings.Add(CountryAbbreviationBotswana,                     "267");
            _CountryCodeMappings.Add(CountryAbbreviationBrazil,                       "55");
            _CountryCodeMappings.Add(CountryAbbreviationBritishVirginIslands,         "1");
            _CountryCodeMappings.Add(CountryAbbreviationBrunei,                       "673");
            _CountryCodeMappings.Add(CountryAbbreviationBulgaria,                     "359");
            _CountryCodeMappings.Add(CountryAbbreviationBurkinaFaso,                  "226");
            _CountryCodeMappings.Add(CountryAbbreviationBurmaMyanmar,                 "95");
            _CountryCodeMappings.Add(CountryAbbreviationBurundi,                      "257");
            _CountryCodeMappings.Add(CountryAbbreviationCambodia,                     "855");
            _CountryCodeMappings.Add(CountryAbbreviationCameroon,                     "237");
            _CountryCodeMappings.Add(CountryAbbreviationCanada,                       "1");
            _CountryCodeMappings.Add(CountryAbbreviationCapeVerde,                    "238");
            _CountryCodeMappings.Add(CountryAbbreviationCaymanIslands,                "1");
            _CountryCodeMappings.Add(CountryAbbreviationCentralAfricanRepublic,       "236");
            _CountryCodeMappings.Add(CountryAbbreviationChad,                         "235");
            _CountryCodeMappings.Add(CountryAbbreviationChile,                        "56");
            _CountryCodeMappings.Add(CountryAbbreviationChina,                        "86");
            _CountryCodeMappings.Add(CountryAbbreviationChristmasIsland,              "61");
            _CountryCodeMappings.Add(CountryAbbreviationCocosKeelingIslands,          "61");
            _CountryCodeMappings.Add(CountryAbbreviationColombia,                     "57");
            _CountryCodeMappings.Add(CountryAbbreviationComoros,                      "269");
            _CountryCodeMappings.Add(CountryAbbreviationCookIslands,                  "682");
            _CountryCodeMappings.Add(CountryAbbreviationCostaRica,                    "506");
            _CountryCodeMappings.Add(CountryAbbreviationCroatia,                      "385");
            _CountryCodeMappings.Add(CountryAbbreviationCuba,                         "53");
            _CountryCodeMappings.Add(CountryAbbreviationCyprus,                       "357");
            _CountryCodeMappings.Add(CountryAbbreviationCzechRepublic,                "420");
            _CountryCodeMappings.Add(CountryAbbreviationDemocraticRepublicoftheCongo, "243");
            _CountryCodeMappings.Add(CountryAbbreviationDenmark,                      "45");
            _CountryCodeMappings.Add(CountryAbbreviationDjibouti,                     "253");
            _CountryCodeMappings.Add(CountryAbbreviationDominica,                     "1");
            _CountryCodeMappings.Add(CountryAbbreviationDominicanRepublic,            "1");
            _CountryCodeMappings.Add(CountryAbbreviationEcuador,                      "593");
            _CountryCodeMappings.Add(CountryAbbreviationEgypt,                        "20");
            _CountryCodeMappings.Add(CountryAbbreviationElSalvador,                   "503");
            _CountryCodeMappings.Add(CountryAbbreviationEquatorialGuinea,             "240");
            _CountryCodeMappings.Add(CountryAbbreviationEritrea,                      "291");
            _CountryCodeMappings.Add(CountryAbbreviationEstonia,                      "372");
            _CountryCodeMappings.Add(CountryAbbreviationEthiopia,                     "251");
            _CountryCodeMappings.Add(CountryAbbreviationFalklandIslands,              "500");
            _CountryCodeMappings.Add(CountryAbbreviationFaroeIslands,                 "298");
            _CountryCodeMappings.Add(CountryAbbreviationFiji,                         "679");
            _CountryCodeMappings.Add(CountryAbbreviationFinland,                      "358");
            _CountryCodeMappings.Add(CountryAbbreviationFrance,                       "33");
            _CountryCodeMappings.Add(CountryAbbreviationFrenchPolynesia,              "689");
            _CountryCodeMappings.Add(CountryAbbreviationGabon,                        "241");
            _CountryCodeMappings.Add(CountryAbbreviationGambia,                       "220");
            _CountryCodeMappings.Add(CountryAbbreviationGeorgia,                      "995");
            _CountryCodeMappings.Add(CountryAbbreviationGermany,                      "49");
            _CountryCodeMappings.Add(CountryAbbreviationGhana,                        "233");
            _CountryCodeMappings.Add(CountryAbbreviationGibraltar,                    "350");
            _CountryCodeMappings.Add(CountryAbbreviationGreece,                       "30");
            _CountryCodeMappings.Add(CountryAbbreviationGreenland,                    "299");
            _CountryCodeMappings.Add(CountryAbbreviationGrenada,                      "1");
            _CountryCodeMappings.Add(CountryAbbreviationGuam,                         "1");
            _CountryCodeMappings.Add(CountryAbbreviationGuatemala,                    "502");
            _CountryCodeMappings.Add(CountryAbbreviationGuinea,                       "224");
            _CountryCodeMappings.Add(CountryAbbreviationGuineaBissau,                 "245");
            _CountryCodeMappings.Add(CountryAbbreviationGuyana,                       "592");
            _CountryCodeMappings.Add(CountryAbbreviationHaiti,                        "509");
            _CountryCodeMappings.Add(CountryAbbreviationHolySeeVaticanCity,           "39");
            _CountryCodeMappings.Add(CountryAbbreviationHonduras,                     "504");
            _CountryCodeMappings.Add(CountryAbbreviationHongKong,                     "852");
            _CountryCodeMappings.Add(CountryAbbreviationHungary,                      "36");
            _CountryCodeMappings.Add(CountryAbbreviationIceland,                      "354");
            _CountryCodeMappings.Add(CountryAbbreviationIndia,                        "91");
            _CountryCodeMappings.Add(CountryAbbreviationIndonesia,                    "62");
            _CountryCodeMappings.Add(CountryAbbreviationIran,                         "98");
            _CountryCodeMappings.Add(CountryAbbreviationIraq,                         "964");
            _CountryCodeMappings.Add(CountryAbbreviationIreland,                      "353");
            _CountryCodeMappings.Add(CountryAbbreviationIsleofMan,                    "44");
            _CountryCodeMappings.Add(CountryAbbreviationIsrael,                       "972");
            _CountryCodeMappings.Add(CountryAbbreviationItaly,                        "39");
            _CountryCodeMappings.Add(CountryAbbreviationIvoryCoast,                   "225");
            _CountryCodeMappings.Add(CountryAbbreviationJamaica,                      "1");
            _CountryCodeMappings.Add(CountryAbbreviationJapan,                        "81");
            _CountryCodeMappings.Add(CountryAbbreviationJersey,                       "44");
            _CountryCodeMappings.Add(CountryAbbreviationJordan,                       "962");
            _CountryCodeMappings.Add(CountryAbbreviationKazakhstan,                   "7");
            _CountryCodeMappings.Add(CountryAbbreviationKenya,                        "254");
            _CountryCodeMappings.Add(CountryAbbreviationKiribati,                     "686");
            _CountryCodeMappings.Add(CountryAbbreviationKuwait,                       "965");
            _CountryCodeMappings.Add(CountryAbbreviationKyrgyzstan,                   "996");
            _CountryCodeMappings.Add(CountryAbbreviationLaos,                         "856");
            _CountryCodeMappings.Add(CountryAbbreviationLatvia,                       "371");
            _CountryCodeMappings.Add(CountryAbbreviationLebanon,                      "961");
            _CountryCodeMappings.Add(CountryAbbreviationLesotho,                      "266");
            _CountryCodeMappings.Add(CountryAbbreviationLiberia,                      "231");
            _CountryCodeMappings.Add(CountryAbbreviationLibya,                        "218");
            _CountryCodeMappings.Add(CountryAbbreviationLiechtenstein,                "423");
            _CountryCodeMappings.Add(CountryAbbreviationLithuania,                    "370");
            _CountryCodeMappings.Add(CountryAbbreviationLuxembourg,                   "352");
            _CountryCodeMappings.Add(CountryAbbreviationMacau,                        "853");
            _CountryCodeMappings.Add(CountryAbbreviationMacedonia,                    "389");
            _CountryCodeMappings.Add(CountryAbbreviationMadagascar,                   "261");
            _CountryCodeMappings.Add(CountryAbbreviationMalawi,                       "265");
            _CountryCodeMappings.Add(CountryAbbreviationMalaysia,                     "60");
            _CountryCodeMappings.Add(CountryAbbreviationMaldives,                     "960");
            _CountryCodeMappings.Add(CountryAbbreviationMali,                         "223");
            _CountryCodeMappings.Add(CountryAbbreviationMalta,                        "356");
            _CountryCodeMappings.Add(CountryAbbreviationMarshallIslands,              "692");
            _CountryCodeMappings.Add(CountryAbbreviationMauritania,                   "222");
            _CountryCodeMappings.Add(CountryAbbreviationMauritius,                    "230");
            _CountryCodeMappings.Add(CountryAbbreviationMayotte,                      "262");
            _CountryCodeMappings.Add(CountryAbbreviationMexico,                       "52");
            _CountryCodeMappings.Add(CountryAbbreviationMicronesia,                   "691");
            _CountryCodeMappings.Add(CountryAbbreviationMoldova,                      "373");
            _CountryCodeMappings.Add(CountryAbbreviationMonaco,                       "377");
            _CountryCodeMappings.Add(CountryAbbreviationMongolia,                     "976");
            _CountryCodeMappings.Add(CountryAbbreviationMontenegro,                   "382");
            _CountryCodeMappings.Add(CountryAbbreviationMontserrat,                   "1");
            _CountryCodeMappings.Add(CountryAbbreviationMorocco,                      "212");
            _CountryCodeMappings.Add(CountryAbbreviationMozambique,                   "258");
            _CountryCodeMappings.Add(CountryAbbreviationNamibia,                      "264");
            _CountryCodeMappings.Add(CountryAbbreviationNauru,                        "674");
            _CountryCodeMappings.Add(CountryAbbreviationNepal,                        "977");
            _CountryCodeMappings.Add(CountryAbbreviationNetherlands,                  "31");
            _CountryCodeMappings.Add(CountryAbbreviationNetherlandsAntilles,          "599");
            _CountryCodeMappings.Add(CountryAbbreviationNewCaledonia,                 "687");
            _CountryCodeMappings.Add(CountryAbbreviationNewZealand,                   "64");
            _CountryCodeMappings.Add(CountryAbbreviationNicaragua,                    "505");
            _CountryCodeMappings.Add(CountryAbbreviationNiger,                        "227");
            _CountryCodeMappings.Add(CountryAbbreviationNigeria,                      "234");
            _CountryCodeMappings.Add(CountryAbbreviationNiue,                         "683");
            _CountryCodeMappings.Add(CountryAbbreviationNorthKorea,                   "850");
            _CountryCodeMappings.Add(CountryAbbreviationNorthernMarianaIslands,       "1");
            _CountryCodeMappings.Add(CountryAbbreviationNorway,                       "47");
            _CountryCodeMappings.Add(CountryAbbreviationOman,                         "968");
            _CountryCodeMappings.Add(CountryAbbreviationPakistan,                     "92");
            _CountryCodeMappings.Add(CountryAbbreviationPalau,                        "680");
            _CountryCodeMappings.Add(CountryAbbreviationPanama,                       "507");
            _CountryCodeMappings.Add(CountryAbbreviationPapuaNewGuinea,               "675");
            _CountryCodeMappings.Add(CountryAbbreviationParaguay,                     "595");
            _CountryCodeMappings.Add(CountryAbbreviationPeru,                         "51");
            _CountryCodeMappings.Add(CountryAbbreviationPhilippines,                  "63");
            _CountryCodeMappings.Add(CountryAbbreviationPitcairnIslands,              "870");
            _CountryCodeMappings.Add(CountryAbbreviationPoland,                       "48");
            _CountryCodeMappings.Add(CountryAbbreviationPortugal,                     "351");
            _CountryCodeMappings.Add(CountryAbbreviationPuertoRico,                   "1");
            _CountryCodeMappings.Add(CountryAbbreviationQatar,                        "974");
            _CountryCodeMappings.Add(CountryAbbreviationRepublicoftheCongo,           "242");
            _CountryCodeMappings.Add(CountryAbbreviationRomania,                      "40");
            _CountryCodeMappings.Add(CountryAbbreviationRussia,                       "7");
            _CountryCodeMappings.Add(CountryAbbreviationRwanda,                       "250");
            _CountryCodeMappings.Add(CountryAbbreviationSaintBarthelemy,              "590");
            _CountryCodeMappings.Add(CountryAbbreviationSaintHelena,                  "290");
            _CountryCodeMappings.Add(CountryAbbreviationSaintKittsandNevis,           "1");
            _CountryCodeMappings.Add(CountryAbbreviationSaintLucia,                   "1");
            _CountryCodeMappings.Add(CountryAbbreviationSaintMartin,                  "1");
            _CountryCodeMappings.Add(CountryAbbreviationSaintPierreandMiquelon,       "508");
            _CountryCodeMappings.Add(CountryAbbreviationSaintVincentandtheGrenadines, "1");
            _CountryCodeMappings.Add(CountryAbbreviationSamoa,                        "685");
            _CountryCodeMappings.Add(CountryAbbreviationSanMarino,                    "378");
            _CountryCodeMappings.Add(CountryAbbreviationSaoTomeandPrincipe,           "239");
            _CountryCodeMappings.Add(CountryAbbreviationSaudiArabia,                  "966");
            _CountryCodeMappings.Add(CountryAbbreviationSenegal,                      "221");
            _CountryCodeMappings.Add(CountryAbbreviationSerbia,                       "381");
            _CountryCodeMappings.Add(CountryAbbreviationSeychelles,                   "248");
            _CountryCodeMappings.Add(CountryAbbreviationSierraLeone,                  "232");
            _CountryCodeMappings.Add(CountryAbbreviationSingapore,                    "65");
            _CountryCodeMappings.Add(CountryAbbreviationSlovakia,                     "421");
            _CountryCodeMappings.Add(CountryAbbreviationSlovenia,                     "386");
            _CountryCodeMappings.Add(CountryAbbreviationSolomonIslands,               "677");
            _CountryCodeMappings.Add(CountryAbbreviationSomalia,                      "252");
            _CountryCodeMappings.Add(CountryAbbreviationSouthAfrica,                  "27");
            _CountryCodeMappings.Add(CountryAbbreviationSouthKorea,                   "82");
            _CountryCodeMappings.Add(CountryAbbreviationSpain,                        "34");
            _CountryCodeMappings.Add(CountryAbbreviationSriLanka,                     "94");
            _CountryCodeMappings.Add(CountryAbbreviationSudan,                        "249");
            _CountryCodeMappings.Add(CountryAbbreviationSuriname,                     "597");
            _CountryCodeMappings.Add(CountryAbbreviationSwaziland,                    "268");
            _CountryCodeMappings.Add(CountryAbbreviationSweden,                       "46");
            _CountryCodeMappings.Add(CountryAbbreviationSwitzerland,                  "41");
            _CountryCodeMappings.Add(CountryAbbreviationSyria,                        "963");
            _CountryCodeMappings.Add(CountryAbbreviationTaiwan,                       "886");
            _CountryCodeMappings.Add(CountryAbbreviationTajikistan,                   "992");
            _CountryCodeMappings.Add(CountryAbbreviationTanzania,                     "255");
            _CountryCodeMappings.Add(CountryAbbreviationThailand,                     "66");
            _CountryCodeMappings.Add(CountryAbbreviationTimorLeste,                   "670");
            _CountryCodeMappings.Add(CountryAbbreviationTogo,                         "228");
            _CountryCodeMappings.Add(CountryAbbreviationTokelau,                      "690");
            _CountryCodeMappings.Add(CountryAbbreviationTonga,                        "676");
            _CountryCodeMappings.Add(CountryAbbreviationTrinidadandTobago,            "1");
            _CountryCodeMappings.Add(CountryAbbreviationTunisia,                      "216");
            _CountryCodeMappings.Add(CountryAbbreviationTurkey,                       "90");
            _CountryCodeMappings.Add(CountryAbbreviationTurkmenistan,                 "993");
            _CountryCodeMappings.Add(CountryAbbreviationTurksandCaicosIslands,        "1");
            _CountryCodeMappings.Add(CountryAbbreviationTuvalu,                       "688");
            _CountryCodeMappings.Add(CountryAbbreviationUganda,                       "256");
            _CountryCodeMappings.Add(CountryAbbreviationUkraine,                      "380");
            _CountryCodeMappings.Add(CountryAbbreviationUnitedArabEmirates,           "971");
            _CountryCodeMappings.Add(CountryAbbreviationUnitedKingdom,                "44");
            _CountryCodeMappings.Add(CountryAbbreviationUnitedStates,                 "1");
            _CountryCodeMappings.Add(CountryAbbreviationUruguay,                      "598");
            _CountryCodeMappings.Add(CountryAbbreviationUSVirginIslands,              "1");
            _CountryCodeMappings.Add(CountryAbbreviationUzbekistan,                   "998");
            _CountryCodeMappings.Add(CountryAbbreviationVanuatu,                      "678");
            _CountryCodeMappings.Add(CountryAbbreviationVenezuela,                    "58");
            _CountryCodeMappings.Add(CountryAbbreviationVietnam,                      "84");
            _CountryCodeMappings.Add(CountryAbbreviationWallisandFutuna,              "681");
            _CountryCodeMappings.Add(CountryAbbreviationYemen,                        "967");
            _CountryCodeMappings.Add(CountryAbbreviationZambia,                       "260");
            _CountryCodeMappings.Add(CountryAbbreviationZimbabwe,                     "263");
        }
    }
}
