//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllYourTextsUi {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class DisplayOptions : global::System.Configuration.ApplicationSettingsBase {
        
        private static DisplayOptions defaultInstance = ((DisplayOptions)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DisplayOptions())));
        
        public static DisplayOptions Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HideEmptyConversations {
            get {
                return ((bool)(this["HideEmptyConversations"]));
            }
            set {
                this["HideEmptyConversations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MergeContacts {
            get {
                return ((bool)(this["MergeContacts"]));
            }
            set {
                this["MergeContacts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HourMinSecAmPm")]
        public global::AllYourTextsUi.Framework.TimeDisplayFormat TimeDisplayFormat {
            get {
                return ((global::AllYourTextsUi.Framework.TimeDisplayFormat)(this["TimeDisplayFormat"]));
            }
            set {
                this["TimeDisplayFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AlphabeticalByContact")]
        public global::AllYourTextsUi.Framework.ConversationSorting ConversationSorting {
            get {
                return ((global::AllYourTextsUi.Framework.ConversationSorting)(this["ConversationSorting"]));
            }
            set {
                this["ConversationSorting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PromptForPhoneChoice {
            get {
                return ((bool)(this["PromptForPhoneChoice"]));
            }
            set {
                this["PromptForPhoneChoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PhoneDataPath {
            get {
                return ((string)(this["PhoneDataPath"]));
            }
            set {
                this["PhoneDataPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PromptForSyncTroubleshooting {
            get {
                return ((bool)(this["PromptForSyncTroubleshooting"]));
            }
            set {
                this["PromptForSyncTroubleshooting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LoadMmsAttachments {
            get {
                return ((bool)(this["LoadMmsAttachments"]));
            }
            set {
                this["LoadMmsAttachments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WarnAboutMoreRecentSync {
            get {
                return ((bool)(this["WarnAboutMoreRecentSync"]));
            }
            set {
                this["WarnAboutMoreRecentSync"] = value;
            }
        }
    }
}
